% =========================================================================
% Experiment 12 (): Complexity and Statistical Significance
%
% This is a POST-PROCESSING experiment. It reuses the paired realizations
% already generated by Experiment 7 instead of rerunning the same expensive
% algorithms on a second Monte Carlo set. This guarantees that the runtime,
% objective and significance tables refer to the same executions shown in
% the algorithm-validation figure.
% =========================================================================
clear; close all; clc;
t_total=tic;
env_mode=getenv('RET_RIS_RUN_MODE');
if isempty(env_mode); RUN_MODE='paper'; else; RUN_MODE=lower(env_mode); end
cfg=unified_ret_ris_isac_config(RUN_MODE);
root=fileparts(mfilename('fullpath')); if isempty(root); root=pwd; end
addpath(root); addpath(fullfile(root,'function'));

results_dir=fullfile(root,'results');
source_file=fullfile(results_dir,sprintf('exp7_algorithm_convergence_%s.mat',lower(RUN_MODE)));
if ~exist(source_file,'file')
    error(['Experiment 7 result file is missing: %s\nRun ', ...
        'exp7_algorithm_comparison_convergence_final.m first.'],source_file);
end
D=load(source_file);
required={'labels','Obj','Pcomm','Feasible','Runtime'};
for ii=1:numel(required)
    if ~isfield(D,required{ii}); error('Experiment 7 file lacks field %s.',required{ii}); end
end
if isfield(D,'main_idx'); idx=D.main_idx(:).'; else; idx=[1 2 3 5 size(D.Obj,2)]; end
labels=D.labels(idx); Obj=D.Obj(:,idx); Pcomm=D.Pcomm(:,idx);
Feasible=D.Feasible(:,idx); Runtime=D.Runtime(:,idx);
S=numel(labels); proposed=S;
% Solver telemetry is produced by Exp.7 with the identical runtime accounting
% path. Missing fields are tolerated for backward compatibility, but the final
% locked release is expected to contain all of them.
innerMed=select_field(D,'InnerSolveMedian',idx,NaN);
cvxMed=select_field(D,'CVXAttemptsMedian',idx,NaN);
fallbackMed=select_field(D,'FallbacksMedian',idx,NaN);
fallbackRateMed=select_field(D,'FallbackRateMedian',idx,NaN);
fpiIterMed=select_field(D,'FPIIterationsMedian',idx,NaN);
pdGapMed=select_field(D,'PrimalDualGapMedian',idx,NaN);
solverWallMed=select_field(D,'SolverWallMedian',idx,NaN);
if isfield(D,'SolverMode'); SolverMode=string(D.SolverMode); else; SolverMode=string(cfg.comm_solver_default); end
if isfield(D,'RuntimeAccountingPolicy'); RuntimeAccountingPolicy=string(D.RuntimeAccountingPolicy); else; RuntimeAccountingPolicy=string(cfg.comm_solver_runtime_accounting); end
Common=all(Feasible,2); mask=repmat(Common,1,S);
[muObj,loObj,hiObj,nObj]=masked_mean_ci_to_db(Obj,mask,1);
[muPc,loPc,hiPc]=masked_mean_ci_to_db(Pcomm,mask,1e-3);
[runMed,runQ1,runQ3]=median_iqr(Runtime);
FeaRate=100*mean(Feasible,1);

Bidx=1:S-1; B=numel(Bidx);
meanGain=nan(B,1); ciLo=meanGain; ciHi=meanGain; pT=meanGain;
pW=meanGain; nPair=zeros(B,1); medianGain=meanGain;
for b=1:B
    st=paired_significance_test(Obj(Common,proposed),Obj(Common,b), ...
        'db_ratio',cfg.significance_alpha_exp12);
    meanGain(b)=st.mean; ciLo(b)=st.ci_low; ciHi(b)=st.ci_high;
    pT(b)=st.p_ttest; pW(b)=st.p_wilcoxon; nPair(b)=st.n;
    medianGain(b)=st.median;
end
pWHolm=holm_adjust(pW); pTHolm=holm_adjust(pT);

% Complexity descriptors for the final locked MA-RCG-MF implementation.
% The default exact communication-QoS inner solve is no longer a generic
% SOCP call: uplink-downlink duality uses a fixed-point iteration whose main
% step solves an M-by-M linear system with K right-hand sides. The hybrid
% backend validates SINR + primal-dual gap and falls back to CVX only on a
% numerical failure. Hence
%   C_FPI = O(I_FPI (M^3 + M^2 K) + K^3)
% while the conservative fallback remains the legacy SOCP complexity.
M=cfg.M; K=cfg.K; N=cfg.N; T=cfg.T; L=numel(cfg.theta_tilt_range);
Ifpi=cfg.comm_duality_max_iter;
Cfpi=Ifpi*(M^3+M^2*K)+K^3;
Cso=sqrt(K)*(M*K)^3;
Cproxy=N*M*(K+T)+M^3;
Q=cfg.exp7_bcs_phase_levels; Blk=cfg.exp7_bcs_blocks; Sw=cfg.exp7_bcs_sweeps;
I=cfg.max_ao_iter; Lloc=2*cfg.tilt_local_half_window+1;
R0=max(cfg.num_phase_trials,4);
Fgeo=numel(cfg.proposed_stage1_geodesic_fractions);
qStageMax=cfg.proposed_stage1_exact_topk_max;
stage1Upper=3*R0 + I*min(Fgeo*Lloc,qStageMax);
% V2 Stage-II exact-solve upper bound. Proxy candidates are cheap and do not
% invoke the communication solver. Every block is visited sequentially, but
% no more than v2_exact_topk_max candidates per block are evaluated exactly.
if isfield(cfg,'proposed_stage2_variant') && strcmpi(cfg.proposed_stage2_variant,'sequential_mf_atr')
    v2B=cfg.v2_blocks;
    v2S=cfg.v2_max_sweeps;
    v2Q=cfg.v2_exact_topk_max;
    v2Ret=cfg.v2_ret_exact_topk_max;
    refineUpper=double(cfg.proposed_mechanism_fallback)+v2S*(v2Ret+v2B*v2Q);
    v2LocalCand=2*numel(cfg.v2_local_fractions);
    v2GlobalCand=max(cfg.v2_global_probe_levels-1,0);
    v2ProxyUpper=cfg.v2_global_probe_sweeps*v2B*(v2LocalCand+v2GlobalCand) + ...
        max(v2S-cfg.v2_global_probe_sweeps,0)*v2B*v2LocalCand;
else
    Bsch=cfg.proposed_polish_blocks_schedule(:).';
    QmaxSch=cfg.proposed_polish_exact_topk_max_schedule(:).';
    R=numel(Bsch);
    retMax=cfg.proposed_polish_ret_exact_topk_max;
    refineUpper=double(cfg.proposed_mechanism_fallback)+sum(retMax+QmaxSch(1:min(R,numel(QmaxSch))));
    if numel(QmaxSch)<R; refineUpper=refineUpper+(R-numel(QmaxSch))*(retMax+QmaxSch(end)); end
    v2ProxyUpper=NaN;
end

solveProxy=nan(1,S); orders=cell(1,S); spaceOrders=cell(1,S);
observedExact=nan(1,S);
if isfield(D,'Stage1ExactEvals')
    stage1Obs=median_finite(D.Stage1ExactEvals);
else
    stage1Obs=NaN;
end
if isfield(D,'TotalExactEvals')
    proposedObs=median_finite(D.TotalExactEvals);
else
    proposedObs=NaN;
end
for ss=1:S
    nm=char(labels{ss});
    if contains(nm,'Fixed RET, No RIS')
        solveProxy(ss)=1; observedExact(ss)=1;
        orders{ss}='O(C_FPI)';
        spaceOrders{ss}='O(MK+M^2)';
    elseif contains(nm,'Fixed RET, RIS-RadarSNR')
        solveProxy(ss)=R0+2*I;
        orders{ss}='O((R_0+I_phi)C_FPI + I_phi C_proxy)';
        spaceOrders{ss}='O(NM+NK+MK+M^2)';
    elseif contains(nm,'Sequential RET then RIS')
        solveProxy(ss)=L+R0+2*I;
        orders{ss}='O((L_theta+R_0+I_phi)C_FPI)';
        spaceOrders{ss}='O(NM+NK+MK+M^2)';
    elseif contains(nm,'block-coordinate')
        solveProxy(ss)=stage1Upper+Sw*(max(Lloc-1,0)+Blk*max(Q-1,1));
        if isfield(D,'BCSExactEvals'); observedExact(ss)=median_finite(D.BCSExactEvals); end
        orders{ss}='O(Stage-I + I_BCS[(L_loc-1)+B(Q-1)]C_FPI)';
        spaceOrders{ss}='O(NM+NK+MK+M^2)';
    elseif contains(nm,'Stage-I RCG-AO')
        solveProxy(ss)=stage1Upper; observedExact(ss)=stage1Obs;
        orders{ss}='O(I_AO[F L_loc C_proxy + Q_A C_FPI])';
        spaceOrders{ss}='O(NM+NK+MK+M^2)';
    elseif contains(nm,'MA-RCG-MF')
        solveProxy(ss)=stage1Upper+refineUpper; observedExact(ss)=proposedObs;
        if isfield(cfg,'proposed_stage2_variant') && strcmpi(cfg.proposed_stage2_variant,'sequential_mf_atr')
            orders{ss}='O(Stage-I + S[B L_{proxy} C_{proxy} + B Q_A C_{FPI}])';
            spaceOrders{ss}='O(NM+NK+MK+M^2+L_{proxy}N)';
        else
            orders{ss}='O(Stage-I + sum_r[B_r L_r C_proxy + Q_r C_FPI])';
            spaceOrders{ss}='O(NM+NK+MK+M^2+Q_r N)';
        end
    else
        solveProxy(ss)=NaN; orders{ss}='See Exp.7 implementation';
        spaceOrders{ss}='See implementation';
    end
end
relativeProxy=solveProxy/solveProxy(1);
Tcomplexity=table(string(labels(:)),string(orders(:)),string(spaceOrders(:)), ...
    solveProxy(:),observedExact(:),innerMed(:),cvxMed(:),fallbackMed(:),fallbackRateMed(:), ...
    fpiIterMed(:),pdGapMed(:),solverWallMed(:),relativeProxy(:),repmat(Cfpi,S,1), ...
    repmat(Cproxy,S,1),repmat(Cso,S,1),runMed(:),runQ1(:),runQ3(:), ...
    repmat(SolverMode,S,1),repmat(RuntimeAccountingPolicy,S,1), ...
    'VariableNames',{'Algorithm','Dominant_time_order','Space_order', ...
    'Exact_inner_solve_upper_proxy','Observed_median_candidate_exact_evals', ...
    'Observed_median_inner_solver_calls','CVX_attempts_median','Hybrid_fallbacks_median', ...
    'Hybrid_fallback_rate_percent','Mean_FPI_iterations_median','Mean_primal_dual_gap_median', ...
    'Comm_solver_wall_median_s','Relative_solve_proxy','C_FPI_worst_iter_proxy', ...
    'C_proxy_numeric_proxy','Legacy_C_SOCP_proxy','Runtime_median_s','Runtime_Q1_s', ...
    'Runtime_Q3_s','Common_solver_mode','Runtime_accounting_policy'});
Tperformance=table(string(labels(:)),muObj(:),loObj(:),hiObj(:), ...
    muPc(:),loPc(:),hiPc(:),FeaRate(:),nObj(:), ...
    'VariableNames',{'Algorithm','RadarSNR_Mean_dB','CI95_Low_dB', ...
    'CI95_High_dB','Pcomm_Mean_dBm','Pcomm_CI95_Low_dBm', ...
    'Pcomm_CI95_High_dBm','Feasibility_percent','Common_samples'});
Tsignificance=table(string(labels(Bidx).'),meanGain,medianGain,ciLo,ciHi, ...
    pT,pTHolm,pW,pWHolm,nPair,pWHolm<cfg.significance_alpha_exp12, ...
    'VariableNames',{'Baseline','ProposedMinusBaseline_Mean_dB', ...
    'Median_dB','CI95_Low_dB','CI95_High_dB','Paired_t_p', ...
    'Paired_t_Holm_p','Wilcoxon_p','Wilcoxon_Holm_p', ...
    'Paired_samples','Significant_after_Holm'});

% Bring the independent duality-vs-CVX accuracy check into the same report.
validation_file=fullfile(results_dir,sprintf('comm_solver_validation_%s.mat',lower(RUN_MODE)));
TsolverValidation=table(); TsolverValidationSummary=table();
if exist(validation_file,'file')
    V=load(validation_file);
    if isfield(V,'report'); TsolverValidation=V.report; end
    if isfield(V,'ValidationSummary'); TsolverValidationSummary=V.ValidationSummary; end
else
    warning('Solver validation file not found: %s. Run validate_comm_solver_duality first.',validation_file);
end

disp(Tcomplexity); disp(Tperformance); disp(Tsignificance);
if ~isempty(TsolverValidationSummary); disp(TsolverValidationSummary); end
matfile=fullfile(results_dir,sprintf('exp12_complexity_significance_%s.mat',lower(RUN_MODE)));
save(matfile,'cfg','labels','idx','Obj','Pcomm','Feasible','Runtime','Common', ...
    'muObj','loObj','hiObj','runMed','runQ1','runQ3','Tcomplexity', ...
    'Tperformance','Tsignificance','solveProxy','observedExact','relativeProxy', ...
    'stage1Upper','refineUpper','v2ProxyUpper','Cfpi','Cproxy','Cso','source_file','SolverMode','RuntimeAccountingPolicy', ...
    'innerMed','cvxMed','fallbackMed','fallbackRateMed','fpiIterMed','pdGapMed','solverWallMed', ...
    'TsolverValidation','TsolverValidationSummary','validation_file');
writetable(Tcomplexity,fullfile(results_dir,sprintf('exp12_complexity_%s.csv',lower(RUN_MODE))));
writetable(Tperformance,fullfile(results_dir,sprintf('exp12_performance_%s.csv',lower(RUN_MODE))));
writetable(Tsignificance,fullfile(results_dir,sprintf('exp12_significance_%s.csv',lower(RUN_MODE))));
if ~isempty(TsolverValidation); writetable(TsolverValidation,fullfile(results_dir,sprintf('exp12_solver_validation_%s.csv',lower(RUN_MODE)))); end
if ~isempty(TsolverValidationSummary); writetable(TsolverValidationSummary,fullfile(results_dir,sprintf('exp12_solver_validation_summary_%s.csv',lower(RUN_MODE)))); end
fprintf('Experiment 12 post-processing complete in %.1f s. Source: %s\n',toc(t_total),source_file);

function v=select_field(D,name,idx,default)
if isfield(D,name)
    z=D.(name); z=z(:).';
    if max(idx)<=numel(z); v=z(idx); else; v=repmat(default,1,numel(idx)); end
else
    v=repmat(default,1,numel(idx));
end
end

function m=median_finite(x)
x=x(isfinite(x)); if isempty(x); m=NaN; else; m=median(x); end
end

function pAdj=holm_adjust(p)
p=p(:); pAdj=nan(size(p)); ids=find(isfinite(p)); if isempty(ids); return; end
[ps,ord]=sort(p(ids)); adj=zeros(size(ps)); running=0;
for j=1:numel(ps)
    running=max(running,(numel(ps)-j+1)*ps(j)); adj(j)=min(running,1);
end
back=zeros(size(ids)); back(ord)=adj; pAdj(ids)=back;
end

function [med,q1,q3]=median_iqr(X)
med=nan(1,size(X,2)); q1=med; q3=med;
for j=1:size(X,2)
    v=X(:,j); v=v(isfinite(v));
    if ~isempty(v); med(j)=median(v); q1(j)=empirical_quantile(v,0.25); q3(j)=empirical_quantile(v,0.75); end
end
end
